db = db.getSiblingDB("corona_travel")

// db.place.createIndex({ place_id: 1 }, { unique: true })
db.places.insert({ name: "Moscow", place_id: "moscow", pos: [55.749792, 37.632495] })
db.places.insert({ name: "Madrid", place_id: "madrid", pos: [40.416775, -3.703790] })
db.places.insert({ name: "New York", place_id: "ny", pos: [40.730610, -73.935242] })
db.places.insert({ name: "Canberra", place_id: "ca", pos: [-35.27583, 149.12383] })
db.places.insert({ name: "Baku", place_id: "bak", pos: [40.3905, 49.86683] })
db.places.insert({ name: "Vienna", place_id: "vien", pos: [48.184517, 16.311865] })
db.places.insert({ name: "Buenos Aires", place_id: "buen", pos: [34.603625,-58.369523] })
db.places.insert({ name: "Minsk", place_id: "minsk", pos: [50.8467, 4.3525] })
db.places.insert({ name: "Sofia", place_id: "sofia", pos: [42.699368, 23.323177] })

db.facts.insert({ name: "Req Square", description: "Red Square was built in 16-th century", fact_id: "moscow_red_sqr", pos: [55.749792, 37.632495] })
db.facts.insert({ name: "Manhattan", description: "Manhattan is historical center on NY", fact_id: "ny_manh", pos: [40.730610, -73.935242] })
db.facts.insert({ name: "The Royal Palace of Madrid", description: "The Royal Palace of Madrid is the official residence of the Spanish royal family at the city of Madrid, although now used only for state ceremonies", fact_id: "madrid_palace", pos: [40.417953, -3.714312] })
db.facts.insert({ name: "City Hill", description: "City Hill is a five hectare landscaped hill located in the centre of Canberra and surrounded by Vernon Circle", fact_id: "city_hill_Canberra", pos: [-35.27583, 149.12383] })
db.facts.insert({ name: "The Heydar Aliyev Center", description: "The Heydar Aliyev Center is a 57,500 m2 building complex in Baku, Azerbaijan designed by Iraqi-British architect Zaha Hadid and noted for its distinctive architecture and flowing, curved style that eschews sharp angles", fact_id: "thac", pos: [40.3905, 49.86683] })
db.facts.insert({ name: "Palais Schönborn", description: "Palais Schönburg is a magnificent baroque jewel located in the centre of Vienna, boasting a wonderfully large and serene garden away from the hustle and bustle of the city. ", fact_id: "p_schon", pos: [48.184517, 16.311865] })
db.facts.insert({ name: "Centro Cultural Kirchner", description: "The Kirchner Cultural Centre is a cultural centre located in Buenos Aires, Argentina. It is the largest of Latin America, and the third or fourth largest in the world.", fact_id: "cent_cult_kirch", pos: [34.603625,-58.369523] })
db.facts.insert({ name: "Belarusian National Arts Museum", description: "The National Art Museum is a cultural house of Belarus", fact_id: "nat_art_mus", pos: [53.8984747, 27.5607685] })
db.facts.insert({ name: "The Grand-Place", description: "The Grand-Place is the central square of the City of Brussels", fact_id: "gr_pal", pos: [50.8467, 4.3525] })
db.facts.insert({ name: "Sofia History Museum", description: "The Sofia History Museum is housed in the former building of the Central Mineral Baths and is devoted to ethnography, archaeology, economy, and cultural life in Sofia and its region", fact_id: "shm", pos: [42.699368, 23.323177] })

